import type { BillingCycle } from '@vpsknow/shared';

/**
 * Public VMISS WHMCS PID catalog used when app.vmiss.com is Cloudflare-blocked.
 * Specs/prices sourced from published affiliate plan tables (not live stock).
 * Stock status from this catalog is intentionally omitted — callers decide.
 */
export interface VmissCatalogPlan {
  readonly pid: string;
  readonly planName: string;
  readonly location: string;
  readonly cpuCores: number;
  readonly ramMb: number;
  readonly storageGb: number;
  readonly bandwidthTb: number;
  readonly portMbps: number;
  readonly priceCents: number;
  readonly currency: 'CAD';
  readonly billingCycle: BillingCycle;
}

export const VMISS_CATALOG: readonly VmissCatalogPlan[] = [
  {
    pid: '32',
    planName: 'US.LA.TRI.Basic',
    location: 'Los Angeles',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 10,
    bandwidthTb: 0.5,
    portMbps: 200,
    priceCents: 500,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '33',
    planName: 'US.LA.TRI.Core',
    location: 'Los Angeles',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 15,
    bandwidthTb: 1.0,
    portMbps: 200,
    priceCents: 1000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '34',
    planName: 'US.LA.TRI.Pro',
    location: 'Los Angeles',
    cpuCores: 1,
    ramMb: 2048,
    storageGb: 20,
    bandwidthTb: 1.5,
    portMbps: 300,
    priceCents: 1600,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '35',
    planName: 'US.LA.TRI.Elite',
    location: 'Los Angeles',
    cpuCores: 2,
    ramMb: 4096,
    storageGb: 40,
    bandwidthTb: 2.5,
    portMbps: 300,
    priceCents: 3000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '36',
    planName: 'US.LA.TRI.Ultra',
    location: 'Los Angeles',
    cpuCores: 4,
    ramMb: 8192,
    storageGb: 80,
    bandwidthTb: 4.0,
    portMbps: 500,
    priceCents: 6000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '7',
    planName: 'US.LA.CN2.Basic',
    location: 'Los Angeles',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 10,
    bandwidthTb: 0.3,
    portMbps: 200,
    priceCents: 600,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '8',
    planName: 'US.LA.CN2.Core',
    location: 'Los Angeles',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 15,
    bandwidthTb: 0.6,
    portMbps: 200,
    priceCents: 1200,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '9',
    planName: 'US.LA.CN2.Pro',
    location: 'Los Angeles',
    cpuCores: 1,
    ramMb: 2048,
    storageGb: 20,
    bandwidthTb: 1.0,
    portMbps: 500,
    priceCents: 2000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '10',
    planName: 'US.LA.CN2.Elite',
    location: 'Los Angeles',
    cpuCores: 2,
    ramMb: 4096,
    storageGb: 40,
    bandwidthTb: 1.6,
    portMbps: 500,
    priceCents: 3800,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '11',
    planName: 'US.LA.CN2.Ultra',
    location: 'Los Angeles',
    cpuCores: 4,
    ramMb: 8192,
    storageGb: 80,
    bandwidthTb: 2.8,
    portMbps: 1000,
    priceCents: 7500,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '57',
    planName: 'US.LA.9929.Basic',
    location: 'Los Angeles',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 10,
    bandwidthTb: 0.5,
    portMbps: 200,
    priceCents: 500,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '58',
    planName: 'US.LA.9929.Core',
    location: 'Los Angeles',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 15,
    bandwidthTb: 1.0,
    portMbps: 200,
    priceCents: 1000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '59',
    planName: 'US.LA.9929.Pro',
    location: 'Los Angeles',
    cpuCores: 1,
    ramMb: 2048,
    storageGb: 20,
    bandwidthTb: 1.5,
    portMbps: 300,
    priceCents: 1600,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '60',
    planName: 'US.LA.9929.Elite',
    location: 'Los Angeles',
    cpuCores: 2,
    ramMb: 4096,
    storageGb: 40,
    bandwidthTb: 2.5,
    portMbps: 500,
    priceCents: 3000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '61',
    planName: 'US.LA.9929.Ultra',
    location: 'Los Angeles',
    cpuCores: 4,
    ramMb: 8192,
    storageGb: 80,
    bandwidthTb: 4.0,
    portMbps: 500,
    priceCents: 6000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '44',
    planName: 'US.LA.CMIN2.Basic',
    location: 'Los Angeles',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 10,
    bandwidthTb: 0.4,
    portMbps: 200,
    priceCents: 500,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '45',
    planName: 'US.LA.CMIN2.Core',
    location: 'Los Angeles',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 15,
    bandwidthTb: 0.8,
    portMbps: 200,
    priceCents: 1000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '46',
    planName: 'US.LA.CMIN2.Pro',
    location: 'Los Angeles',
    cpuCores: 1,
    ramMb: 2048,
    storageGb: 20,
    bandwidthTb: 1.2,
    portMbps: 300,
    priceCents: 1600,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '47',
    planName: 'US.LA.CMIN2.Elite',
    location: 'Los Angeles',
    cpuCores: 2,
    ramMb: 4096,
    storageGb: 40,
    bandwidthTb: 2.0,
    portMbps: 500,
    priceCents: 3000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '48',
    planName: 'US.LA.CMIN2.Ultra',
    location: 'Los Angeles',
    cpuCores: 4,
    ramMb: 8192,
    storageGb: 80,
    bandwidthTb: 3.2,
    portMbps: 500,
    priceCents: 6000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '50',
    planName: 'CN.HK.BGP.Basic',
    location: 'Hong Kong',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 10,
    bandwidthTb: 0.3,
    portMbps: 100,
    priceCents: 500,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '53',
    planName: 'CN.HK.BGP.Core',
    location: 'Hong Kong',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 15,
    bandwidthTb: 0.6,
    portMbps: 100,
    priceCents: 850,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '54',
    planName: 'CN.HK.BGP.Pro',
    location: 'Hong Kong',
    cpuCores: 1,
    ramMb: 2048,
    storageGb: 20,
    bandwidthTb: 1.0,
    portMbps: 100,
    priceCents: 1600,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '55',
    planName: 'CN.HK.BGP.Elite',
    location: 'Hong Kong',
    cpuCores: 2,
    ramMb: 4096,
    storageGb: 40,
    bandwidthTb: 1.6,
    portMbps: 100,
    priceCents: 3000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '56',
    planName: 'CN.HK.BGP.Ultra',
    location: 'Hong Kong',
    cpuCores: 4,
    ramMb: 8192,
    storageGb: 80,
    bandwidthTb: 3.0,
    portMbps: 100,
    priceCents: 6000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '83',
    planName: 'CN.HK.BGP-V2.Basic',
    location: 'Hong Kong',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 10,
    bandwidthTb: 0.4,
    portMbps: 100,
    priceCents: 500,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '84',
    planName: 'CN.HK.BGP-V2.Core',
    location: 'Hong Kong',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 15,
    bandwidthTb: 0.8,
    portMbps: 100,
    priceCents: 1000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '85',
    planName: 'CN.HK.BGP-V2.Pro',
    location: 'Hong Kong',
    cpuCores: 1,
    ramMb: 2048,
    storageGb: 20,
    bandwidthTb: 1.2,
    portMbps: 200,
    priceCents: 1600,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '86',
    planName: 'CN.HK.BGP-V2.Elite',
    location: 'Hong Kong',
    cpuCores: 2,
    ramMb: 4096,
    storageGb: 40,
    bandwidthTb: 2.0,
    portMbps: 200,
    priceCents: 3000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '87',
    planName: 'CN.HK.BGP-V2.Ultra',
    location: 'Hong Kong',
    cpuCores: 4,
    ramMb: 8192,
    storageGb: 80,
    bandwidthTb: 3.6,
    portMbps: 300,
    priceCents: 6000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '38',
    planName: 'CN.HK.INTL.Basic',
    location: 'Hong Kong',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 10,
    bandwidthTb: 1.0,
    portMbps: 500,
    priceCents: 3000,
    currency: 'CAD',
    billingCycle: 'annually',
  },
  {
    pid: '39',
    planName: 'CN.HK.INTL.Core',
    location: 'Hong Kong',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 15,
    bandwidthTb: 2.0,
    portMbps: 500,
    priceCents: 6000,
    currency: 'CAD',
    billingCycle: 'annually',
  },
  {
    pid: '40',
    planName: 'CN.HK.INTL.Pro',
    location: 'Hong Kong',
    cpuCores: 1,
    ramMb: 2048,
    storageGb: 20,
    bandwidthTb: 3.0,
    portMbps: 800,
    priceCents: 5400,
    currency: 'CAD',
    billingCycle: 'semi-annually',
  },
  {
    pid: '42',
    planName: 'CN.HK.INTL.Elite',
    location: 'Hong Kong',
    cpuCores: 2,
    ramMb: 4096,
    storageGb: 40,
    bandwidthTb: 4.0,
    portMbps: 1000,
    priceCents: 7200,
    currency: 'CAD',
    billingCycle: 'semi-annually',
  },
  {
    pid: '43',
    planName: 'CN.HK.INTL.Ultra',
    location: 'Hong Kong',
    cpuCores: 4,
    ramMb: 8192,
    storageGb: 80,
    bandwidthTb: 5.0,
    portMbps: 1000,
    priceCents: 1800,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '101',
    planName: 'JP.TKY.TRI.Basic',
    location: 'Tokyo',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 10,
    bandwidthTb: 0.3,
    portMbps: 100,
    priceCents: 1200,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '102',
    planName: 'JP.TKY.TRI.Core',
    location: 'Tokyo',
    cpuCores: 1,
    ramMb: 2048,
    storageGb: 15,
    bandwidthTb: 0.6,
    portMbps: 100,
    priceCents: 2400,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '103',
    planName: 'JP.TKY.TRI.Pro',
    location: 'Tokyo',
    cpuCores: 1,
    ramMb: 3072,
    storageGb: 20,
    bandwidthTb: 1.0,
    portMbps: 200,
    priceCents: 3800,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '104',
    planName: 'JP.TKY.TRI.Elite',
    location: 'Tokyo',
    cpuCores: 2,
    ramMb: 4096,
    storageGb: 40,
    bandwidthTb: 1.6,
    portMbps: 200,
    priceCents: 7500,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '105',
    planName: 'JP.TKY.TRI.Ultra',
    location: 'Tokyo',
    cpuCores: 4,
    ramMb: 8192,
    storageGb: 80,
    bandwidthTb: 2.8,
    portMbps: 300,
    priceCents: 15000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '67',
    planName: 'JP.TKY.IIJ.Basic',
    location: 'Tokyo',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 10,
    bandwidthTb: 0.5,
    portMbps: 500,
    priceCents: 500,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '68',
    planName: 'JP.TKY.IIJ.Core',
    location: 'Tokyo',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 15,
    bandwidthTb: 0.8,
    portMbps: 500,
    priceCents: 850,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '69',
    planName: 'JP.TKY.IIJ.Pro',
    location: 'Tokyo',
    cpuCores: 1,
    ramMb: 2048,
    storageGb: 20,
    bandwidthTb: 1.5,
    portMbps: 750,
    priceCents: 1600,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '70',
    planName: 'JP.TKY.IIJ.Elite',
    location: 'Tokyo',
    cpuCores: 2,
    ramMb: 4096,
    storageGb: 40,
    bandwidthTb: 2.5,
    portMbps: 750,
    priceCents: 3000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '71',
    planName: 'JP.TKY.IIJ.Ultra',
    location: 'Tokyo',
    cpuCores: 4,
    ramMb: 8192,
    storageGb: 80,
    bandwidthTb: 4.0,
    portMbps: 1000,
    priceCents: 6000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '72',
    planName: 'JP.TKY.BGP.Basic',
    location: 'Tokyo',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 10,
    bandwidthTb: 0.4,
    portMbps: 500,
    priceCents: 500,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '73',
    planName: 'JP.TKY.BGP.Core',
    location: 'Tokyo',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 15,
    bandwidthTb: 0.8,
    portMbps: 500,
    priceCents: 850,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '74',
    planName: 'JP.TKY.BGP.Pro',
    location: 'Tokyo',
    cpuCores: 1,
    ramMb: 2048,
    storageGb: 20,
    bandwidthTb: 1.2,
    portMbps: 750,
    priceCents: 1600,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '75',
    planName: 'JP.TKY.BGP.Elite',
    location: 'Tokyo',
    cpuCores: 2,
    ramMb: 4096,
    storageGb: 40,
    bandwidthTb: 2.0,
    portMbps: 750,
    priceCents: 3000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '76',
    planName: 'JP.TKY.BGP.Ultra',
    location: 'Tokyo',
    cpuCores: 4,
    ramMb: 8192,
    storageGb: 80,
    bandwidthTb: 3.2,
    portMbps: 1000,
    priceCents: 6000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '25',
    planName: 'JP.OSA.IIJ.Basic',
    location: 'Osaka',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 10,
    bandwidthTb: 0.5,
    portMbps: 500,
    priceCents: 500,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '26',
    planName: 'JP.OSA.IIJ.Core',
    location: 'Osaka',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 15,
    bandwidthTb: 1.0,
    portMbps: 500,
    priceCents: 1000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '27',
    planName: 'JP.OSA.IIJ.Pro',
    location: 'Osaka',
    cpuCores: 1,
    ramMb: 2048,
    storageGb: 20,
    bandwidthTb: 1.5,
    portMbps: 750,
    priceCents: 1600,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '28',
    planName: 'JP.OSA.IIJ.Elite',
    location: 'Osaka',
    cpuCores: 2,
    ramMb: 4096,
    storageGb: 40,
    bandwidthTb: 2.5,
    portMbps: 750,
    priceCents: 3000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '29',
    planName: 'JP.OSA.IIJ.Ultra',
    location: 'Osaka',
    cpuCores: 4,
    ramMb: 8192,
    storageGb: 80,
    bandwidthTb: 4.0,
    portMbps: 1000,
    priceCents: 6000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '62',
    planName: 'KR.SEL.BGP.Basic',
    location: 'Seoul',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 10,
    bandwidthTb: 0.3,
    portMbps: 50,
    priceCents: 500,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '63',
    planName: 'KR.SEL.BGP.Core',
    location: 'Seoul',
    cpuCores: 1,
    ramMb: 1024,
    storageGb: 15,
    bandwidthTb: 0.6,
    portMbps: 50,
    priceCents: 1000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '64',
    planName: 'KR.SEL.BGP.Pro',
    location: 'Seoul',
    cpuCores: 1,
    ramMb: 2048,
    storageGb: 20,
    bandwidthTb: 1.0,
    portMbps: 60,
    priceCents: 1600,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '65',
    planName: 'KR.SEL.BGP.Elite',
    location: 'Seoul',
    cpuCores: 2,
    ramMb: 4096,
    storageGb: 40,
    bandwidthTb: 1.6,
    portMbps: 60,
    priceCents: 3000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
  {
    pid: '66',
    planName: 'KR.SEL.BGP.Ultra',
    location: 'Seoul',
    cpuCores: 4,
    ramMb: 8192,
    storageGb: 80,
    bandwidthTb: 2.6,
    portMbps: 75,
    priceCents: 6000,
    currency: 'CAD',
    billingCycle: 'monthly',
  },
] as const;

